name: Coverage report
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - develop
      - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 90
